import { z } from "zod";

export const FailureSourceSchema = z.enum([
  "github",
  "azure-devops",
  "gitlab",
  "bitbucket",
  "circleci",
  "jenkins",
  "generic",
]);
export type FailureSource = z.infer<typeof FailureSourceSchema>;

export const RepositorySchema = z.object({
  owner: z.string(),
  name: z.string(),
  url: z.string().url(),
  defaultBranch: z.string().optional(),
  id: z.string().optional(),
  ownerId: z.string().optional(),
  provider: z.string().optional(),
  visibility: z.string().optional(),
  clean: z.string().optional(),
  tfvcWorkspace: z.string().optional(),
  gitSubmoduleCheckout: z.string().optional(),
});
export type Repository = z.infer<typeof RepositorySchema>;

export const CommitSchema = z.object({
  sha: z.string(),
  url: z.string().url(),
  message: z.string().optional(),
  author: z.string().optional(),
  authorEmail: z.string().optional(),
  requestedForId: z.string().optional(),
  queuedById: z.string().optional(),
});
export type Commit = z.infer<typeof CommitSchema>;

export const PullRequestSchema = z.object({
  number: z.number().int().positive(),
  url: z.string().url(),
  title: z.string(),
  author: z.string(),
});
export type PullRequest = z.infer<typeof PullRequestSchema>;

export const PipelineSchema = z.object({
  name: z.string(),
  url: z.string().url(),
  runUrl: z.string().url().optional(),
  runId: z.string(),
  runNumber: z.number().int().nonnegative().optional(),
  stage: z.string().optional(),
  job: z.string().optional(),
  step: z.string().optional(),
  task: z.string().optional(),
  runnerType: z.string().optional(),
  runnerOs: z.string().optional(),
  runnerArch: z.string().optional(),
  agentPool: z.string().optional(),
  runnerName: z.string().optional(),
  agentMachineName: z.string().optional(),
  retryCount: z.number().int().nonnegative().optional(),
  runAttempt: z.number().int().nonnegative().optional(),
  jobName: z.string().optional(),
  definitionVersion: z.string().optional(),
  definitionId: z.string().optional(),
  reason: z.string().optional(),
  sourcesDirectory: z.string().optional(),
  binariesDirectory: z.string().optional(),
  artifactStagingDirectory: z.string().optional(),
  containerId: z.string().optional(),
  repositoryLocalPath: z.string().optional(),
  workflowRef: z.string().optional(),
  workflowSha: z.string().optional(),
  runnerEnvironment: z.string().optional(),
  runnerDebug: z.boolean().optional(),
  retentionDays: z.number().int().optional(),
  actorId: z.string().optional(),
  triggeringActor: z.string().optional(),
  triggeringActorId: z.string().optional(),
  refType: z.string().optional(),
  refProtected: z.boolean().optional(),
  agentId: z.string().optional(),
  agentJobStatus: z.string().optional(),
  agentBuildDirectory: z.string().optional(),
  agentHomeDirectory: z.string().optional(),
  agentTempDirectory: z.string().optional(),
  agentToolsDirectory: z.string().optional(),
  agentWorkFolder: z.string().optional(),
  agentContainerMapping: z.string().optional(),
  agentReleaseDirectory: z.string().optional(),
  agentRootDirectory: z.string().optional(),
  stagingDirectory: z.string().optional(),
  testResultsDirectory: z.string().optional(),
  cronScheduleDisplayName: z.string().optional(),
  pipelineWorkspace: z.string().optional(),
  stageRequestedBy: z.string().optional(),
  stageRequestedForId: z.string().optional(),
  sourceTfvcShelveset: z.string().optional(),
  triggeredByBuildId: z.string().optional(),
  triggeredByDefinitionId: z.string().optional(),
  triggeredByDefinitionName: z.string().optional(),
  triggeredByBuildNumber: z.string().optional(),
  triggeredByProjectId: z.string().optional(),
  teamProjectId: z.string().optional(),
  teamProject: z.string().optional(),
  buildUri: z.string().optional(),
  buildNumber: z.string().optional(),
  environmentId: z.string().optional(),
  environmentResourceName: z.string().optional(),
  environmentResourceId: z.string().optional(),
  strategyName: z.string().optional(),
  strategyCycleName: z.string().optional(),
  checksStageAttempt: z.string().optional(),
  systemWorkFolder: z.string().optional(),
  systemCollectionId: z.string().optional(),
  systemCollectionUri: z.string().optional(),
  systemTeamFoundationCollectionUri: z.string().optional(),
  systemDebug: z.string().optional(),
  systemDefaultWorkingDirectory: z.string().optional(),
  systemHostType: z.string().optional(),
  systemJobDisplayName: z.string().optional(),
  systemJobId: z.string().optional(),
  systemJobName: z.string().optional(),
  systemPhaseAttempt: z.string().optional(),
  systemPhaseDisplayName: z.string().optional(),
  systemPhaseName: z.string().optional(),
  systemPlanId: z.string().optional(),
  systemStageAttempt: z.string().optional(),
  systemStageDisplayName: z.string().optional(),
  systemStageName: z.string().optional(),
  systemTimelineId: z.string().optional(),
  tfBuild: z.string().optional(),
  prIsFork: z.string().optional(),
  prId: z.string().optional(),
  prNumber: z.string().optional(),
  prTargetBranchName: z.string().optional(),
  prSourceBranch: z.string().optional(),
  prSourceCommitId: z.string().optional(),
  prSourceRepoUri: z.string().optional(),
  prTargetBranch: z.string().optional(),
  releaseDeploymentRequestedFor: z.string().optional(),
  releaseDeploymentRequestedForEmail: z.string().optional(),
  releaseDeploymentId: z.string().optional(),
  releaseDefinitionEnvironmentId: z.string().optional(),
  releaseDefinitionId: z.string().optional(),
  releaseDefinitionName: z.string().optional(),
  releaseEnvironmentId: z.string().optional(),
  releaseEnvironmentName: z.string().optional(),
  releasePrimaryArtifactSourceAlias: z.string().optional(),
  releaseDescription: z.string().optional(),
  releaseId: z.string().optional(),
  requestedFor: z.string().optional(),
  requestedForEmail: z.string().optional(),
  requestedForId: z.string().optional(),
  queuedBy: z.string().optional(),
  queuedById: z.string().optional(),
  sourceBranchName: z.string().optional(),
  fullSourceBranch: z.string().optional(),
  sourceVersionMessage: z.string().optional(),
  repositoryId: z.string().optional(),
  repositoryProvider: z.string().optional(),
  repositoryUri: z.string().optional(),
  releaseName: z.string().optional(),
  releaseUri: z.string().optional(),
  releaseArtifacts: z.record(z.string(), z.any()).optional(),
  triggerId: z.string().optional(),
  triggerName: z.string().optional(),
  action: z.string().optional(),
  actionPath: z.string().optional(),
  actionRepository: z.string().optional(),
  baseRef: z.string().optional(),
  headRef: z.string().optional(),
  runnerTemp: z.string().optional(),
  runnerToolCache: z.string().optional(),
  runnerWorkspace: z.string().optional(),
  workspace: z.string().optional(),
  jobStatus: z.string().optional(),
  jobContainer: z.string().optional(),
  jobServices: z.string().optional(),
  strategyJobIndex: z.number().int().optional(),
  strategyJobTotal: z.number().int().optional(),
  actionRef: z.string().optional(),
  actionStatus: z.string().optional(),
  repositoryGitUrl: z.string().optional(),
  repositoryClean: z.string().optional(),
  repositoryGitSubmoduleCheckout: z.string().optional(),
  secretSource: z.string().optional(),
  // GitLab CI fields
  gitlabProjectId: z.string().optional(),
  gitlabProjectUrl: z.string().optional(),
  gitlabProjectTitle: z.string().optional(),
  gitlabProjectDescription: z.string().optional(),
  gitlabProjectVisibility: z.string().optional(),
  gitlabProjectNamespace: z.string().optional(),
  gitlabProjectRootNamespace: z.string().optional(),
  gitlabPipelineId: z.string().optional(),
  gitlabPipelineIid: z.string().optional(),
  gitlabPipelineUrl: z.string().optional(),
  gitlabPipelineSource: z.string().optional(),
  gitlabPipelineName: z.string().optional(),
  gitlabPipelineCreatedAt: z.string().optional(),
  gitlabJobId: z.string().optional(),
  gitlabJobName: z.string().optional(),
  gitlabJobStage: z.string().optional(),
  gitlabJobStatus: z.string().optional(),
  gitlabJobStartedAt: z.string().optional(),
  gitlabJobImage: z.string().optional(),
  gitlabJobTimeout: z.string().optional(),
  gitlabJobTags: z.string().optional(),
  gitlabCommitTitle: z.string().optional(),
  gitlabCommitDescription: z.string().optional(),
  gitlabCommitAuthor: z.string().optional(),
  gitlabCommitTimestamp: z.string().optional(),
  gitlabCommitBeforeSha: z.string().optional(),
  gitlabEnvironmentTier: z.string().optional(),
  gitlabEnvironmentUrl: z.string().optional(),
  gitlabEnvironmentAction: z.string().optional(),
  gitlabMergeRequestIid: z.string().optional(),
  gitlabMergeRequestId: z.string().optional(),
  gitlabMergeRequestTitle: z.string().optional(),
  gitlabMergeRequestEvent: z.string().optional(),
  gitlabMergeRequestSourceBranch: z.string().optional(),
  gitlabMergeRequestTargetBranch: z.string().optional(),
  gitlabMergeRequestAssignees: z.string().optional(),
  gitlabMergeRequestLabels: z.string().optional(),
  gitlabMergeRequestMilestone: z.string().optional(),
  gitlabRunnerId: z.string().optional(),
  gitlabRunnerDescription: z.string().optional(),
  gitlabRunnerTags: z.string().optional(),
  gitlabRunnerVersion: z.string().optional(),
  gitlabUserLogin: z.string().optional(),
  gitlabUserName: z.string().optional(),
  gitlabUserEmail: z.string().optional(),
  gitlabUserId: z.string().optional(),
  gitlabServerUrl: z.string().optional(),
  gitlabServerVersion: z.string().optional(),
  // Bitbucket Pipelines fields
  bitbucketBuildNumber: z.string().optional(),
  bitbucketCloneDir: z.string().optional(),
  bitbucketCommit: z.string().optional(),
  bitbucketWorkspace: z.string().optional(),
  bitbucketWorkspaceUuid: z.string().optional(),
  bitbucketRepoOwner: z.string().optional(),
  bitbucketRepoOwnerUuid: z.string().optional(),
  bitbucketRepoSlug: z.string().optional(),
  bitbucketRepoUuid: z.string().optional(),
  bitbucketRepoFullName: z.string().optional(),
  bitbucketRepoIsPrivate: z.boolean().optional(),
  bitbucketBranch: z.string().optional(),
  bitbucketTag: z.string().optional(),
  bitbucketBookmark: z.string().optional(),
  bitbucketParallelStep: z.number().int().optional(),
  bitbucketParallelStepCount: z.number().int().optional(),
  bitbucketPrId: z.string().optional(),
  bitbucketPrDestinationBranch: z.string().optional(),
  bitbucketPrDestinationCommit: z.string().optional(),
  bitbucketMergeQueuePrIds: z.string().optional(),
  bitbucketGitHttpOrigin: z.string().optional(),
  bitbucketGitSshOrigin: z.string().optional(),
  bitbucketExitCode: z.number().int().optional(),
  bitbucketStepUuid: z.string().optional(),
  bitbucketPipelineUuid: z.string().optional(),
  bitbucketDeploymentEnvironment: z.string().optional(),
  bitbucketDeploymentEnvironmentUuid: z.string().optional(),
  bitbucketProjectKey: z.string().optional(),
  bitbucketProjectUuid: z.string().optional(),
  bitbucketStepTriggererUuid: z.string().optional(),
  bitbucketStepRunNumber: z.number().int().optional(),
  bitbucketPackagesUsername: z.string().optional(),
  bitbucketDockerHost: z.string().optional(),
  bitbucketTriggerPipelineUuid: z.string().optional(),
  bitbucketTriggerPipelineRunUuid: z.string().optional(),
  bitbucketTriggerStepUuid: z.string().optional(),
  bitbucketTriggerPipelineSelectorType: z.string().optional(),
  bitbucketTriggerPipelineSelectorPattern: z.string().optional(),
  bitbucketTriggerPipelineStatus: z.string().optional(),
  bitbucketTriggerDeploymentUuid: z.string().optional(),
  bitbucketTriggerDeploymentStatus: z.string().optional(),
  bitbucketTriggerDeploymentEnvironmentName: z.string().optional(),
  bitbucketTriggerPackagesPackageType: z.string().optional(),
  bitbucketTriggerPackagesPackageName: z.string().optional(),
  bitbucketTriggerPackagesArtifactName: z.string().optional(),
  bitbucketTriggerFixFlakyTestTargetBranch: z.string().optional(),
  bitbucketTriggerFixFlakyTestSourceBranch: z.string().optional(),
  bitbucketTriggerTestCaseFqdn: z.string().optional(),
  bitbucketTriggerTestCaseUuid: z.string().optional(),
});
export type Pipeline = z.infer<typeof PipelineSchema>;

export const FailureDetailsSchema = z.object({
  exitCode: z.number().int().optional(),
  errorMessage: z.string().optional(),
  failedStep: z.string().optional(),
  failedCommand: z.string().optional(),
  stackTrace: z.string().optional(),
  logs: z.string().default(""),
  logsTruncated: z.boolean().default(false),
});
export type FailureDetails = z.infer<typeof FailureDetailsSchema>;

export const FailureEventSchema = z.object({
  source: FailureSourceSchema,
  startedAt: z.string().datetime(),
  failedAt: z.string().datetime(),
  durationMs: z.number().int().nonnegative().optional(),
  queueTimeMs: z.number().int().nonnegative().optional(),
  pipeline: PipelineSchema,
  repository: RepositorySchema,
  commit: CommitSchema,
  branch: z.string(),
  pullRequest: PullRequestSchema.optional(),
  environment: z.string().optional(),
  triggeredBy: z.string().optional(),
  eventName: z.string().optional(),
  apiUrl: z.string().optional(),
  graphqlUrl: z.string().optional(),
  metadata: z.record(z.string(), z.string()).default({}),
  explicitFields: z.array(z.string()).default([]),
  failure: FailureDetailsSchema,
  eventPayload: z.any().optional(),
});

export type FailureEvent = z.infer<typeof FailureEventSchema>;
