import { z } from "zod";

export const FailureSourceSchema = z.enum(["github", "azure-devops"]);
export type FailureSource = z.infer<typeof FailureSourceSchema>;

export const RepositorySchema = z.object({
  owner: z.string(),
  name: z.string(),
  url: z.string().url(),
  defaultBranch: z.string().optional(),
  id: z.string().optional(),
  ownerId: z.string().optional(),
  provider: z.string().optional(),
  visibility: z.string().optional(),
  clean: z.string().optional(),
  tfvcWorkspace: z.string().optional(),
  gitSubmoduleCheckout: z.string().optional(),
});
export type Repository = z.infer<typeof RepositorySchema>;

export const CommitSchema = z.object({
  sha: z.string(),
  url: z.string().url(),
  message: z.string().optional(),
  author: z.string().optional(),
  authorEmail: z.string().optional(),
  requestedForId: z.string().optional(),
  queuedById: z.string().optional(),
});
export type Commit = z.infer<typeof CommitSchema>;

export const PullRequestSchema = z.object({
  number: z.number().int().positive(),
  url: z.string().url(),
  title: z.string(),
  author: z.string(),
});
export type PullRequest = z.infer<typeof PullRequestSchema>;

export const PipelineSchema = z.object({
  name: z.string(),
  url: z.string().url(),
  runId: z.string(),
  runNumber: z.number().int().nonnegative().optional(),
  stage: z.string().optional(),
  job: z.string().optional(),
  step: z.string().optional(),
  task: z.string().optional(),
  runnerType: z.string().optional(),
  runnerOs: z.string().optional(),
  runnerArch: z.string().optional(),
  agentPool: z.string().optional(),
  runnerName: z.string().optional(),
  agentMachineName: z.string().optional(),
  retryCount: z.number().int().nonnegative().optional(),
  runAttempt: z.number().int().nonnegative().optional(),
  jobName: z.string().optional(),
  definitionVersion: z.string().optional(),
  definitionId: z.string().optional(),
  sourcesDirectory: z.string().optional(),
  binariesDirectory: z.string().optional(),
  artifactStagingDirectory: z.string().optional(),
  containerId: z.string().optional(),
  repositoryLocalPath: z.string().optional(),
  workflowRef: z.string().optional(),
  workflowSha: z.string().optional(),
  runnerEnvironment: z.string().optional(),
  runnerDebug: z.boolean().optional(),
  retentionDays: z.number().int().optional(),
  actorId: z.string().optional(),
  triggeringActor: z.string().optional(),
  triggeringActorId: z.string().optional(),
  refType: z.string().optional(),
  refProtected: z.boolean().optional(),
  agentId: z.string().optional(),
  agentJobStatus: z.string().optional(),
  agentBuildDirectory: z.string().optional(),
  agentHomeDirectory: z.string().optional(),
  agentTempDirectory: z.string().optional(),
  agentToolsDirectory: z.string().optional(),
  agentWorkFolder: z.string().optional(),
  stagingDirectory: z.string().optional(),
  testResultsDirectory: z.string().optional(),
  cronScheduleDisplayName: z.string().optional(),
  stageRequestedBy: z.string().optional(),
  stageRequestedForId: z.string().optional(),
  triggeredByBuildId: z.string().optional(),
  triggeredByDefinitionId: z.string().optional(),
  triggeredByDefinitionName: z.string().optional(),
  triggeredByBuildNumber: z.string().optional(),
  triggeredByProjectId: z.string().optional(),
  teamProjectId: z.string().optional(),
  environmentId: z.string().optional(),
  environmentResourceName: z.string().optional(),
  environmentResourceId: z.string().optional(),
  strategyName: z.string().optional(),
  strategyCycleName: z.string().optional(),
  systemCollectionId: z.string().optional(),
  systemHostType: z.string().optional(),
  systemJobDisplayName: z.string().optional(),
  systemJobId: z.string().optional(),
  systemPhaseAttempt: z.string().optional(),
  systemPhaseDisplayName: z.string().optional(),
  systemPhaseName: z.string().optional(),
  systemPlanId: z.string().optional(),
  systemStageAttempt: z.string().optional(),
  systemStageDisplayName: z.string().optional(),
  systemStageName: z.string().optional(),
  systemTimelineId: z.string().optional(),
  tfBuild: z.string().optional(),
  prIsFork: z.string().optional(),
  prId: z.string().optional(),
  prNumber: z.string().optional(),
  prTargetBranchName: z.string().optional(),
  prSourceBranch: z.string().optional(),
  prSourceCommitId: z.string().optional(),
  prSourceRepoUri: z.string().optional(),
  prTargetBranch: z.string().optional(),
  triggerId: z.string().optional(),
  triggerName: z.string().optional(),
});
export type Pipeline = z.infer<typeof PipelineSchema>;

export const FailureDetailsSchema = z.object({
  exitCode: z.number().int().optional(),
  errorMessage: z.string().optional(),
  failedStep: z.string().optional(),
  failedCommand: z.string().optional(),
  stackTrace: z.string().optional(),
  logs: z.string().default(""),
  logsTruncated: z.boolean().default(false),
});
export type FailureDetails = z.infer<typeof FailureDetailsSchema>;

export const FailureEventSchema = z.object({
  source: FailureSourceSchema,
  startedAt: z.string().datetime(),
  failedAt: z.string().datetime(),
  durationMs: z.number().int().nonnegative().optional(),
  queueTimeMs: z.number().int().nonnegative().optional(),
  pipeline: PipelineSchema,
  repository: RepositorySchema,
  commit: CommitSchema,
  branch: z.string(),
  pullRequest: PullRequestSchema.optional(),
  environment: z.string().optional(),
  triggeredBy: z.string().optional(),
  eventName: z.string().optional(),
  apiUrl: z.string().optional(),
  failure: FailureDetailsSchema,
});

export type FailureEvent = z.infer<typeof FailureEventSchema>;
