import type { FailureEvent, JiraTicketSpec } from "./types/index.js";
import { maskSecrets } from "./secret-mask.js";

/**
 * Build the markdown ticket description from the event + already-populated fields.
 * Called late in the pipeline, after all enrichers have run.
 */
export function renderDescription(
  event: FailureEvent,
  fields: Partial<JiraTicketSpec>,
  logExcerptLines: number,
  maskLogs: boolean,
): string {
  const out: string[] = [];

  out.push("## PipelineIQ Failure Report");
  out.push("");

  // Failure summary section
  const customFields = fields.customFields ?? {};
  const rca = customFields._rca as string | undefined;
  const remediation = customFields._remediation as string[] | undefined;

  out.push("### Failure Summary");
  out.push(fields.summary ?? "Pipeline failure detected.");
  out.push("");

  if (rca) {
    out.push("### Root Cause");
    out.push(rca);
    out.push("");
  }

  if (remediation && remediation.length > 0) {
    out.push("### Suggested Remediation");
    remediation.forEach((step, i) => out.push(`${i + 1}. ${step}`));
    out.push("");
  }

  out.push("---");
  out.push("");
  out.push("## Pipeline Metadata");
  out.push("| Field | Value |");
  out.push("| --- | --- |");
  out.push(`| Source | ${event.source} |`);
  out.push(`| Pipeline | ${event.pipeline.name} |`);
  out.push(`| Repository | ${event.repository.owner}/${event.repository.name} |`);
  out.push(`| Branch | ${event.branch} |`);
  out.push(`| Commit | ${event.commit.sha.slice(0, 7)} |`);
  if (event.environment) out.push(`| Environment | ${event.environment} |`);
  if (event.pipeline.step) out.push(`| Failed Step | ${event.pipeline.step} |`);
  if (event.pipeline.stage) out.push(`| Failed Stage | ${event.pipeline.stage} |`);
  if (event.failure.exitCode !== undefined) {
    out.push(`| Exit Code | ${event.failure.exitCode} |`);
  }
  if (event.pipeline.retryCount !== undefined) {
    out.push(`| Retry Count | ${event.pipeline.retryCount} |`);
  }
  out.push(`| Triggered By | ${event.triggeredBy ?? "unknown"} |`);
  if (event.durationMs) {
    out.push(`| Duration | ${(event.durationMs / 1000).toFixed(1)}s |`);
  }
  out.push("");

  if (event.failure.errorMessage) {
    out.push("### Error Message");
    out.push("```");
    out.push(event.failure.errorMessage);
    out.push("```");
    out.push("");
  }

  // Log excerpt — trimmed + secret-masked
  if (event.failure.logs) {
    const cleaned = maskLogs ? maskSecrets(event.failure.logs) : event.failure.logs;
    const excerpt = tailLines(cleaned, logExcerptLines);
    out.push("### Relevant Logs");
    if (event.failure.logsTruncated) {
      out.push("> Logs were truncated by the adapter — see attachment for full output.");
    }
    out.push("```log");
    out.push(excerpt);
    out.push("```");
    out.push("");
  }

  // Links
  out.push("### Links");
  // Pipeline/Workflow URL
  out.push(`- [Pipeline Run](${event.pipeline.url})`);
  // Repository URL
  out.push(`- [Repository](${event.repository.url})`);
  // Commit URL
  out.push(`- [Commit](${event.commit.url})`);
  // Pull Request URL (if available)
  if ((event as any).pullRequest) {
    out.push(`- [Pull Request #${(event as any).pullRequest.number}](${(event as any).pullRequest.url})`);
  }
  // Additional external links from fields
  for (const link of fields.externalLinks ?? []) {
    out.push(`- [${link.title}](${link.url})`);
  }
  out.push("");

  // Provenance footer — small, builds trust about which stage produced what.
  if (fields.provenance && Object.keys(fields.provenance).length > 0) {
    out.push("---");
    out.push("");
    out.push(
      `<sub>Generated by PipelineIQ · signature \`${fields.dedupSignature ?? "?"}\`</sub>`,
    );
  }

  return out.join("\n");
}

function tailLines(input: string, n: number): string {
  const lines = input.split("\n");
  if (lines.length <= n) return input;
  return lines.slice(-n).join("\n");
}
